### ISSUE TITLE
config.js not defined on master branch

### ISSUE THREAD

**Issue by sanyamagrawal** [wincent/masochist#80]
```
> server@0.0.1 update-indices /Users/sanyamagrawal/project/relay/masochist/app
> babel-node src/bin/updateIndices.js

module.js:327
    throw err;
    ^

Error: Cannot find module '../../config'
    at Function.Module._resolveFilename (module.js:325:15)
    at Function.Module._load (module.js:276:25)
    at Module.require (module.js:353:17)
    at require (internal/module.js:12:17)
    at Object.<anonymous> (config.js:1:16)
    at Module._compile (module.js:409:26)
    at loader (/Users/sanyamagrawal/project/relay/masochist/app/node_modules/babel-register/lib/node.js:126:5)
    at Object.require.extensions.(anonymous function) [as .js] (/Users/sanyamagrawal/project/relay/masochist/app/node_modules/babel-register/lib/node.js:136:7)
    at Module.load (module.js:343:32)
    at Function.Module._load (module.js:300:12)
    at Module.require (module.js:353:17)
    at require (internal/module.js:12:17)
    at Object.<anonymous> (git.js:8:1)
    at Module._compile (module.js:409:26)
    at loader (/Users/sanyamagrawal/project/relay/masochist/app/node_modules/babel-register/lib/node.js:126:5)
    at Object.require.extensions.(anonymous function) [as .js] (/Users/sanyamagrawal/project/relay/masochist/app/node_modules/babel-register/lib/node.js:136:7)
```

Changing this to common/config causes update-indices npm task to break down.

Can anyone suggest me what to do

**Comment by wincent** [comment]
You need a `config.json` in the `app` directory, telling Masochist the path to a repo from which to read the data. There is [an example provided](https://github.com/wincent/masochist/blob/d1fe9d0458d79e4e5ce7641444314e67f51feb56/app/config.example.json), which just tells Masochist to read data out of the current directory.

**Comment by wincent** [comment]
Going to close this optimistically on the assumption that the above resolves your issue. Let me know if it doesn't.
